R CMD INSTALL Rcpp_0.11.2.tar.gz
R CMD INSTALL RcppEigen_0.3.2.2.0.tar.gz
R CMD INSTALL minqa_1.2.3.tar.gz
R CMD INSTALL modified/nloptr_1.0.4.tar.gz
R CMD INSTALL plyr_1.8.1.tar.gz
R CMD INSTALL lme4_1.1-7.tar.gz
R CMD INSTALL profileModel_0.5-9.tar.gz
R CMD INSTALL brglm_0.5-9.tar.gz
R CMD INSTALL iterators_1.0.7.tar.gz
R CMD INSTALL foreach_1.4.2.tar.gz
R CMD INSTALL stringr_0.6.2.tar.gz
R CMD INSTALL reshape2_1.4.tar.gz
R CMD INSTALL RColorBrewer_1.0-5.tar.gz
R CMD INSTALL dichromat_2.0-0.tar.gz
R CMD INSTALL colorspace_1.2-4.tar.gz
R CMD INSTALL munsell_0.4.2.tar.gz
R CMD INSTALL labeling_0.3.tar.gz
R CMD INSTALL digest_0.6.4.tar.gz
R CMD INSTALL scales_0.2.4.tar.gz
R CMD INSTALL proto_0.3-10.tar.gz
R CMD INSTALL gtools_3.4.1.tar.gz
R CMD INSTALL gtable_0.1.2.tar.gz
R CMD INSTALL ggplot2_1.0.0.tar.gz
R CMD INSTALL modeltools_0.2-21.tar.gz
R CMD INSTALL mvtnorm_1.0-0.tar.gz
R CMD INSTALL plotmo_1.3-3.tar.gz
R CMD INSTALL plotrix_3.5-7.tar.gz
R CMD INSTALL mclust_4.3.tar.gz
R CMD INSTALL flexmix_2.3-11.tar.gz
R CMD INSTALL prabclus_2.2-4.tar.gz
R CMD INSTALL DEoptimR_1.0-1.tar.gz
R CMD INSTALL robustbase_0.91-1.tar.gz
R CMD INSTALL kernlab_0.9-19.tar.gz
R CMD INSTALL trimcluster_0.1-2.tar.gz
R CMD INSTALL zoo_1.7-11.tar.gz
R CMD INSTALL numDeriv_2012.9-1.tar.gz
R CMD INSTALL lava_1.2.6.tar.gz
R CMD INSTALL prodlim_1.4.5.tar.gz
R CMD INSTALL evaluate_0.5.5.tar.gz
R CMD INSTALL mime_0.1.2.tar.gz
R CMD INSTALL markdown_0.7.4.tar.gz
R CMD INSTALL miscTools_0.6-16.tar.gz
R CMD INSTALL sandwich_2.3-2.tar.gz
R CMD INSTALL maxLik_1.2-0.tar.gz
R CMD INSTALL statmod_1.4.20.tar.gz
R CMD INSTALL lmtest_0.9-33.tar.gz
R CMD INSTALL strucchange_1.5-0.tar.gz
R CMD INSTALL coin_1.0-24.tar.gz
R CMD INSTALL BH_1.54.0-4.tar.gz
R CMD INSTALL latticeExtra_0.6-26.tar.gz
R CMD INSTALL BradleyTerry2_1.0-5.tar.gz
R CMD INSTALL DAAG_1.20.tar.gz
R CMD INSTALL DBI_0.3.1.tar.gz
R CMD INSTALL FNN_1.1.tar.gz
R CMD INSTALL Formula_1.1-2.tar.gz
R CMD INSTALL Hmisc_3.14-4.tar.gz
R CMD INSTALL Lahman_3.0-1.tar.gz
R CMD INSTALL MEMSS_0.9-2.tar.gz
R CMD INSTALL PKPDmodels_0.3.2.tar.gz
R CMD INSTALL R6_2.0.tar.gz
R CMD INSTALL RANN_2.4.1.tar.gz
R CMD INSTALL RSQLite_0.11.4.tar.gz
R CMD INSTALL RSQLite.extfuns_0.0.1.tar.gz
R CMD INSTALL RUnit_0.4.26.tar.gz
R CMD INSTALL SparseM_1.05.tar.gz
R CMD INSTALL TH.data_1.0-3.tar.gz
R CMD INSTALL assertthat_0.1.tar.gz
R CMD INSTALL car_2.0-21.tar.gz
R CMD INSTALL caret_6.0-35.tar.gz
R CMD INSTALL chron_2.3-45.tar.gz
R CMD INSTALL coda_0.16-1.tar.gz
R CMD INSTALL combinat_0.0-8.tar.gz
R CMD INSTALL corpcor_1.6.6.tar.gz
R CMD INSTALL data.table_1.9.4.tar.gz
R CMD INSTALL diptest_0.75-5.tar.gz
R CMD INSTALL e1071_1.6-4.tar.gz
R CMD INSTALL earth_3.2-7.tar.gz
R CMD INSTALL ellipse_0.3-8.tar.gz
R CMD INSTALL fastICA_1.2-0.tar.gz
R CMD INSTALL formatR_1.0.tar.gz
R CMD INSTALL fpc_2.1-8.tar.gz
R CMD INSTALL fracdiff_1.4-2.tar.gz
R CMD INSTALL fts_0.9.9.tar.gz
R CMD INSTALL gamm4_0.2-3.tar.gz
R CMD INSTALL gclus_1.3.1.tar.gz
R CMD INSTALL glmnet_2.0-2.tar.gz
R CMD INSTALL highr_0.3.tar.gz
R CMD INSTALL installPackages.sh
R CMD INSTALL intervals_0.14.0.tar.gz
R CMD INSTALL ipred_0.9-3.tar.gz
R CMD INSTALL its_1.1.8.tar.gz
R CMD INSTALL klaR_0.6-12.tar.gz
R CMD INSTALL knitr_1.6.tar.gz
R CMD INSTALL lars_1.2.tar.gz
R CMD INSTALL longmemo_1.0-0.tar.gz
R CMD INSTALL magrittr_1.0.1.tar.gz
R CMD INSTALL maps_2.3-7.tar.gz
R CMD INSTALL mapdata_2.2-3.tar.gz
R CMD INSTALL mda_0.4-4.tar.gz
R CMD INSTALL microbenchmark_1.4-2.tar.gz
R CMD INSTALL mix_1.0-8.tar.gz
R CMD INSTALL mlbench_2.1-1.tar.gz
R CMD INSTALL mlmRev_1.0-6.tar.gz
R CMD INSTALL mlogit_0.2-4.tar.gz
R CMD INSTALL mondate_0.10.01.02.tar.gz
R CMD INSTALL multcomp_1.3-6.tar.gz
R CMD INSTALL optimx_2013.8.6.tar.gz
R CMD INSTALL party_1.0-17.tar.gz
R CMD INSTALL pbkrtest_0.4-0.tar.gz
R CMD INSTALL pls_2.4-3.tar.gz
R CMD INSTALL proxy_0.4-13.tar.gz
R CMD INSTALL pvclust_1.2-2.tar.gz
R CMD INSTALL quadprog_1.5-5.tar.gz
R CMD INSTALL randomForest_4.6-10.tar.gz
R CMD INSTALL rjson_0.2.15.tar.gz
R CMD INSTALL snow_0.3-13.tar.gz
R CMD INSTALL sp_1.0-15.tar.gz
R CMD INSTALL spls_2.2-1.tar.gz
R CMD INSTALL testthat_0.8.1.tar.gz
R CMD INSTALL timeDate_3010.98.tar.gz
R CMD INSTALL timeSeries_3010.97.tar.gz
R CMD INSTALL tis_1.23.tar.gz
R CMD INSTALL tseries_0.10-32.tar.gz
R CMD INSTALL urca_1.2-8.tar.gz
R CMD INSTALL xtable_1.7-4.tar.gz
R CMD INSTALL xts_0.9-7.tar.gz
